name: timescaledb-sink-draft
language: python
variables:
  - name: TIMESCALEDB_USER
    inputType: FreeText
    defaultValue: tsadmin
    required: true
  - name: TIMESCALEDB_HOST
    inputType: FreeText
    defaultValue: timescaledb
    required: true
  - name: TIMESCALEDB_PORT
    inputType: FreeText
    defaultValue: 5432
    required: true
  - name: TIMESCALEDB_PASSWORD
    inputType: Secret
    defaultValue: TIMESCALE_PASSWORD
    required: true
  - name: TIMESCALEDB_DATABASE
    inputType: FreeText
    defaultValue: metrics
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: postgresql-destination
