name: timescaledb-sink-draft
language: python
variables:
  - name: TSDB_INPUT
    inputType: InputTopic
    defaultValue: solar-data
    required: true
  - name: TSDB_HOST
    inputType: FreeText
    defaultValue: timescaledb
    required: true
  - name: TSDB_PORT
    inputType: FreeText
    defaultValue: 5432
    required: true
  - name: TSDB_SCHEMA
    inputType: FreeText
    defaultValue: public
    required: true
  - name: TSDB_BATCH_SIZE
    inputType: FreeText
    defaultValue: 1000
    required: true
  - name: TSDB_CONSUMER_GROUP_NAME
    inputType: FreeText
    defaultValue: timescaledb-consumer-group
    required: true
  - name: TSDB_DBNAME
    inputType: FreeText
    defaultValue: metrics
    required: true
  - name: TSDB_PASSWORD_KEY
    inputType: Secret
    defaultValue: TIMESCALE_PASSWORD
    required: true
  - name: TSDB_TABLE
    inputType: FreeText
    defaultValue: data_sink_och2
    required: true
  - name: TSDB_BATCH_TIMEOUT
    inputType: FreeText
    defaultValue: 1
    required: true
  - name: TSDB_USER
    inputType: FreeText
    defaultValue: tsadmin
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: postgresql-destination
