name: timescaledb-sink-draft
language: python
variables:
  - name: input
    inputType: InputTopic
    required: true
  - name: TIMESCALEDB_USER
    inputType: FreeText
    required: true
  - name: TIMESCALEDB_HOST
    inputType: FreeText
    required: true
  - name: TIMESCALEDB_DATABASE
    inputType: FreeText
    required: true
  - name: TIMESCALEDB_PASSWORD
    inputType: Secret
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: postgresql-destination
