name: ch14
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: solar-data
  - name: CLICKHOUSE_HOST
    inputType: FreeText
    description: ClickHouse server host
    defaultValue: clickhouse-test
  - name: CLICKHOUSE_PORT
    inputType: FreeText
    description: ClickHouse server port
    defaultValue: 8123
  - name: CLICKHOUSE_USER
    inputType: FreeText
    description: ClickHouse username
    defaultValue: clickadmin
  - name: CLICKHOUSE_PASSWORD
    inputType: Secret
    description: ClickHouse password
    defaultValue: CLICKHOUSE_SECRET_KEY
  - name: CLICKHOUSE_DATABASE
    inputType: FreeText
    description: ClickHouse database name
    defaultValue: default
  - name: QUIX_PORTAL_API
    inputType: FreeText
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
