name: google-storage-bucket-source-draft-69qx
language: python
variables:
  - name: output
    inputType: OutputTopic
    defaultValue: s3-data
    required: true
  - name: S3_BUCKET
    inputType: FreeText
    required: true
  - name: S3_REGION
    inputType: FreeText
    required: true
  - name: S3_SECRET
    inputType: Secret
    required: true
  - name: S3_ACCESS_KEY_ID
    inputType: Secret
    required: true
  - name: S3_FOLDER_PATH
    inputType: FreeText
    required: true
  - name: S3_FILE_FORMAT
    inputType: FreeText
    defaultValue: json
    required: true
  - name: S3_FILE_COMPRESSION
    inputType: FreeText
    defaultValue: gzip
    required: true
  - name: GOOGLE_STORAGE_FILE_FORMAT
    inputType: FreeText
  - name: GOOGLE_STORAGE_BUCKET
    inputType: FreeText
  - name: GOOGLE_STORAGE_SECRET_KEY
    inputType: FreeText
  - name: GOOGLE_STORAGE_FOLDER_PATH
    inputType: FreeText
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: s3-source
