name: questdb-hatred
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: transform
  - name: questdb_password
    inputType: FreeText
  - name: questdb_port
    inputType: FreeText
  - name: questdb_host
    inputType: FreeText
  - name: questdb_username
    inputType: FreeText
  - name: questdb_database
    inputType: FreeText
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
