name: questdb-hatred
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: solar-data
  - name: questdb_host
    inputType: FreeText
    description: QuestDB server hostname or IP address
    defaultValue: localhost
  - name: questdb_port
    inputType: FreeText
    description: QuestDB server port
    defaultValue: 8812
  - name: questdb_database
    inputType: FreeText
    description: QuestDB database name
    defaultValue: qdb
  - name: questdb_username
    inputType: FreeText
    description: QuestDB username
    defaultValue: admin
  - name: questdb_password
    inputType: Secret
    description: QuestDB password
    defaultValue: quest
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
