name: questdb-sink-draft-6rl4
language: python
variables:
  - name: QUESTDB_USERNAME
    inputType: FreeText
    required: true
  - name: QUESTDB_DATABASE
    inputType: FreeText
    required: true
  - name: QUESTDB_PASSWORD
    inputType: FreeText
    required: true
  - name: input
    inputType: InputTopic
    defaultValue: solar-data
    required: true
  - name: QUESTDB_HOST
    inputType: FreeText
    required: true
  - name: QUESTDB_TABLE
    inputType: FreeText
    defaultValue: data_sink_eaml
    required: true
  - name: CONSUMER_GROUP_NAME
    inputType: FreeText
    defaultValue: questdb-consumer-group
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: influxdb-3-destination
