name: merlin-puretest
language: python
variables:
  - name: input
    inputType: InputTopic
    multiline: false
    description: Name of the input topic to listen to.
    defaultValue: solar-data
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: transform
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-transformation
