name: google-sheets-source-draft-f4wn
language: python
variables:
  - name: GOOGLE_SHEETS_RANGE
    inputType: FreeText
    multiline: false
    defaultValue: Sheet1!A1:Z100
    required: true
  - name: GCP_SHEETS_API_KEY_SECRET
    inputType: Secret
    defaultValue: GCLOUD_PK_JSON
    required: true
  - name: GOOGLE_SHEETS_DOCUMENT_ID
    inputType: FreeText
    defaultValue: 1i9m16qPwCkrvjE3VXTmm3-v7gNQFGo8nLbRDGtIgFOI
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-source
