name: gcp-test8
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: transform
  - name: GCS_BUCKET_NAME
    inputType: FreeText
  - name: CSV_FILE_PREFIX
    inputType: FreeText
  - name: GCP_CREDENTIALS_JSON
    inputType: FreeText
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
