name: clickhousetest-v8
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: solar-data
  - name: CONSUMER_GROUP
    inputType: FreeText
    defaultValue: starter-sink-consumer
  - name: CLICKHOUSE_BATCH_TIMEOUT
    inputType: FreeText
    defaultValue: 1
  - name: CLICKHOUSE_DATABASE
    inputType: FreeText
  - name: DEBUG_MODE
    inputType: FreeText
  - name: CLICKHOUSE_SECURE
    inputType: FreeText
  - name: CLICKHOUSE_MAX_RETRIES
    inputType: FreeText
  - name: CLICKHOUSE_PORT
    inputType: FreeText
  - name: CLICKHOUSE_PASSWORD
    inputType: FreeText
  - name: CLICKHOUSE_TABLE
    inputType: FreeText
  - name: CLICKHOUSE_USERNAME
    inputType: FreeText
  - name: CLICKHOUSE_HOST
    inputType: FreeText
  - name: CLICKHOUSE_MAX_BATCH_SIZE
    inputType: FreeText
    defaultValue: 1000
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
