name: clickhousetest-v8
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: solar-data
  - name: CONSUMER_GROUP
    inputType: FreeText
    defaultValue: solar_panel_clickhouse_sink
    required: true
  - name: CLICKHOUSE_PASSWORD
    inputType: Secret
    defaultValue: CLICKHOUSE_SECRET_KEY
    required: true
  - name: CLICKHOUSE_SECURE
    inputType: FreeText
    defaultValue: false
    required: true
  - name: CLICKHOUSE_MAX_RETRIES
    inputType: FreeText
    defaultValue: 3
    required: true
  - name: CLICKHOUSE_HOST
    inputType: FreeText
    defaultValue: clickhouse-test
    required: true
  - name: CLICKHOUSE_TABLE
    inputType: FreeText
    defaultValue: solar_panel_data
    required: true
  - name: DEBUG_MODE
    inputType: FreeText
    defaultValue: false
    required: true
  - name: CLICKHOUSE_DATABASE
    inputType: FreeText
    defaultValue: default
    required: true
  - name: CLICKHOUSE_PORT
    inputType: FreeText
    defaultValue: 8123
    required: true
  - name: CLICKHOUSE_USERNAME
    inputType: FreeText
    defaultValue: clickadmin
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
