name: clickhousetest-v12
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: solar-data
  - name: CLICKHOUSE_USERNAME
    inputType: FreeText
    defaultValue: clickpass
    required: true
  - name: CLICKHOUSE_SECURE
    inputType: FreeText
    defaultValue: false
    required: true
  - name: TESTING
    inputType: FreeText
    defaultValue: true
    required: true
  - name: CLICKHOUSE_DATABASE
    inputType: FreeText
    defaultValue: default
    required: true
  - name: CLICKHOUSE_HOST
    inputType: FreeText
    defaultValue: clickhouse-test
    required: true
  - name: CLICKHOUSE_PASSWORD
    inputType: Secret
    defaultValue: CLICKHOUSE_SECRET_KEY
    required: true
  - name: CLICKHOUSE_PORT
    inputType: FreeText
    defaultValue: 8123
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
