name: gcpsink-v1
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: solar-data
  - name: GCP_BUCKET_NAME
    inputType: FreeText
    defaultValue: quix-workflow
    required: true
  - name: GCP_SERVICE_ACCOUNT_KEY
    inputType: Secret
    defaultValue: GCLOUD_PK_JSON
    required: true
  - name: CSV_FILENAME_PREFIX
    inputType: FreeText
    defaultValue: sensor_data
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
