name: gcpsink-v1
language: python
variables:
- name: input
  inputType: InputTopic
  description: Name of the input topic to listen to.
  defaultValue: solar-data
- name: GCP_SERVICE_ACCOUNT_KEY
  inputType: Secret
  description: GCP Service Account JSON key for authentication
  defaultValue: GCLOUD_PK_JSON
- name: GCP_BUCKET_NAME
  inputType: FreeText
  description: Name of the GCP Cloud Storage bucket to write CSV files to
  defaultValue: quix-workflow
- name: CSV_FILENAME_PREFIX
  inputType: FreeText
  description: Prefix for CSV filenames (timestamp will be appended)
  defaultValue: sensor_data
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
