FROM postgres:16

# Set environment variables
ENV PGDATA=/app/state/pgdata
ENV POSTGRES_USER=admin
ENV POSTGRES_DB=quix
ENV POSTGRES_PORT=80  # Add this line

EXPOSE 80  # Change from 5432 to 80

# Copy and set up init script
USER root
COPY init.sh /init.sh
RUN chmod +x /init.sh
ENTRYPOINT ["/init.sh"]