name: hivemq-sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: solar-data
    required: true
  - name: mqtt_topic_root
    inputType: FreeText
    description: The root for messages in MQTT, this can be anything
    defaultValue: solar-data
    required: true
  - name: mqtt_server
    inputType: FreeText
    description: The address of your MQTT server
    defaultValue: 8c070f88f569419db9771e183412ba13.s1.eu.hivemq.cloud
    required: true
  - name: mqtt_port
    inputType: FreeText
    description: The port of your MQTT server
    defaultValue: 8883
    required: true
  - name: mqtt_username
    inputType: FreeText
    description: Username of your MQTT user
    defaultValue: solar
  - name: mqtt_password
    inputType: HiddenText
    description: Password for the MQTT user
    defaultValue: Solar1000000
  - name: mqtt_version
    inputType: FreeText
    description: 'MQTT protocol version: 3.1, 3.1.1, 5'
    defaultValue: 3.1.1
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: mqtt_function.py
libraryItemId: hivemq-destination
