name: gcpcsvv1
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: solar-data
  - name: GCS_PROJECT_ID
    inputType: FreeText
    defaultValue: quix-testing-365012
    required: true
  - name: GCS_FILE_PREFIX
    inputType: FreeText
    defaultValue: solar-data
    required: true
  - name: GCS_BUCKET_NAME
    inputType: FreeText
    defaultValue: quix-workflow
    required: true
  - name: GCS_CREDENTIALS_JSON
    inputType: FreeText
    defaultValue: GCLOUD_PK_JSON
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
