name: stinking-old-cheese
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: solar-data
  - name: QUESTDB_PORT
    inputType: FreeText
    defaultValue: 8812
    required: true
  - name: QUESTDB_USER
    inputType: FreeText
    defaultValue: admin
    required: true
  - name: QUESTDB_HOST
    inputType: FreeText
    defaultValue: questdb
    required: true
  - name: QUESTDB_DATABASE
    inputType: FreeText
    defaultValue: qdb
    required: true
  - name: QUESTDB_TABLE
    inputType: FreeText
    defaultValue: solar_panel_data
    required: true
  - name: QUESTDB_PASSWORD
    inputType: Secret
    defaultValue: QUESTDB_PW
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
