name: google-cloud-storage-source-draft-wmgc
language: python
variables:
  - name: output
    inputType: OutputTopic
    multiline: false
    description: Name of the output topic to write into
    defaultValue: output
    required: true
  - name: GCS_BUCKET_NAME
    inputType: FreeText
    multiline: false
    description: The URI or URL to your S3 bucket
    defaultValue: quix-workflow
    required: true
  - name: GCS_PROJECT_ID
    inputType: FreeText
    multiline: false
    description: The region of your S3 bucket
    required: true
  - name: GCS_KEY_FILE_PATH
    inputType: Secret
    multiline: false
    description: Your AWS secret
    defaultValue: GCLOUD_PK_JSON
    required: true
  - name: GCS_SERVICE_ACCOUNT_EMAIL
    inputType: FreeText
    multiline: false
    description: Your AWS Access Key
    required: true
  - name: GCS_FOLDER_PATH
    inputType: FreeText
    multiline: false
    description: The path to the S3 folder to consume
    defaultValue: /
    required: true
  - name: GCS_FILE_FORMAT
    inputType: FreeText
    multiline: false
    description: The file format of the files
    defaultValue: json
    required: true
  - name: S3_FILE_COMPRESSION
    inputType: FreeText
    description: The type of file compression used for the files
    defaultValue: gzip
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: s3-source
