name: questdb-sink-draft-9ysz
language: python
variables:
  - name: CONSUMER_GROUP_NAME
    inputType: FreeText
    defaultValue: questdb-consumer-group
    required: true
  - name: BUFFER_SIZE
    inputType: FreeText
    required: true
  - name: BUFFER_DELAY
    inputType: FreeText
    required: true
  - name: QUESTDB_PORT
    inputType: FreeText
    defaultValue: 8812
    required: true
  - name: input
    inputType: InputTopic
    defaultValue: solar-data
    required: true
  - name: QUESTDB_HOST
    inputType: FreeText
    defaultValue: questdb
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: influxdb-3-destination
