name: questdb-boy
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: transform
  - name: QUESTDB_HOST
    inputType: FreeText
  - name: QUESTDB_PASSWORD
    inputType: FreeText
  - name: QUESTDB_DATABASE
    inputType: FreeText
  - name: QUESTDB_USERNAME
    inputType: FreeText
  - name: QUESTDB_TABLE
    inputType: FreeText
  - name: QUESTDB_HTTP_PORT
    inputType: FreeText
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
