name: google-storage-bucket-sink-draft
language: python
variables:
  - name: GS_FOLDER_PATH
    inputType: FreeText
    defaultValue: /
    required: true
  - name: GS_BUCKET
    inputType: FreeText
    defaultValue: quix-workflow
    required: true
  - name: GS_API_KEY
    inputType: Secret
    multiline: false
    defaultValue: GCLOUD_PK_JSON
    required: true
  - name: GS_COMPRESSION
    inputType: FreeText
    multiline: false
    defaultValue: None
    required: true
  - name: GS_PROJECT_ID
    inputType: FreeText
    defaultValue: quix-testing-365012
    required: true
  - name: GS_FILE_FORMAT
    inputType: FreeText
    defaultValue: csv
    required: true
  - name: output
    inputType: OutputTopic
    multiline: false
    defaultValue: output
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: s3-iceberg-destination
