name: Starter Sink
language: python
variables:
  - name: input
    inputType: InputTopic
    multiline: false
    description: Name of the input topic to listen to.
    defaultValue: solar-data
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
