name: google-storage-bucket-source-draft-oczj
language: python
variables:
  - name: GS_SECRET_KEY
    inputType: Secret
    defaultValue: GCLOUD_PK_JSON
    required: true
  - name: GS_FILE_FORMAT
    inputType: FreeText
    defaultValue: csv
    required: true
  - name: GS_FOLDER_PATH
    inputType: FreeText
    defaultValue: /
    required: true
  - name: GS_FILE_COMPRESSION
    inputType: FreeText
    defaultValue: none
    required: true
  - name: GS_BUCKET
    inputType: FreeText
    defaultValue: quix-workflow
    required: true
  - name: GS_PROJECT_ID
    inputType: FreeText
    defaultValue: quix-testing-365012
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: s3-source
