name: questdb-sink-draft
language: python
variables:
  - name: QUESTDB_USERNAME
    inputType: FreeText
    defaultValue: admin
    required: true
  - name: QUESTDB_BUFFER_SIZE
    inputType: FreeText
    multiline: false
    defaultValue: 1000
    required: true
  - name: QUESTDB_CONSUMER_GROUP_NAME
    inputType: FreeText
    defaultValue: questdb-consumer-group
    required: true
  - name: QUESTDB_INPUT
    inputType: InputTopic
    defaultValue: solar-data
    required: true
  - name: QUESTDB_BUFFER_TIMEOUT
    inputType: FreeText
    defaultValue: 1
    required: true
  - name: QUESTDB_DATABASE
    inputType: FreeText
    defaultValue: test_db
    required: true
  - name: QUESTDB_PASSWORD_KEY
    inputType: Secret
    defaultValue: QUESTDB_PW
    required: true
  - name: QUESTDB_PORT
    inputType: FreeText
    defaultValue: 8812
    required: true
  - name: QUESTDB_TABLE_NAME
    inputType: FreeText
    defaultValue: data_sink_2oo3
    required: true
  - name: QUESTDB_HOST
    inputType: FreeText
    defaultValue: questdb
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: influxdb-3-destination
