name: questdb-sink-draft
language: python
variables:
  - name: QUESTDB_HOST
    inputType: FreeText
    defaultValue: questdb
    required: true
  - name: BUFFER_SIZE
    inputType: FreeText
    defaultValue: 1000
    required: true
  - name: QUESTDB_PORT
    inputType: FreeText
    multiline: false
    defaultValue: 80
    required: true
  - name: QUESTDB_TABLE_NAME
    inputType: FreeText
    defaultValue: data_sink_ieof
    required: true
  - name: TIMESTAMP_COLUMN
    inputType: FreeText
    defaultValue: timestamp
    required: true
  - name: INPUT_TOPIC
    inputType: InputTopic
    defaultValue: solar-data
    required: true
  - name: CONSUMER_GROUP_NAME
    inputType: FreeText
    defaultValue: questdb-consumer-group
    required: true
  - name: BUFFER_TIMEOUT
    inputType: FreeText
    defaultValue: 1
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: influxdb-3-destination
