name: questdb-sink-draft
language: python
variables:
  - name: QDB_BUFFER_TIMEOUT
    inputType: FreeText
    defaultValue: 1
    required: true
  - name: QDB_BUFFER_SIZE
    inputType: FreeText
    defaultValue: 1000
    required: true
  - name: QDB_CONSUMER_GROUP_NAME
    inputType: FreeText
    defaultValue: questdb-consumer-group
    required: true
  - name: QDB_TABLE_NAME
    inputType: FreeText
    defaultValue: data_sink_5er3
    required: true
  - name: QDB_HOST
    inputType: FreeText
    defaultValue: questdb
    required: true
  - name: QDB_DATABASE
    inputType: FreeText
    defaultValue: qdb
    required: true
  - name: QDB_PORT
    inputType: FreeText
    multiline: false
    defaultValue: 8812
    required: true
  - name: QDB_TOKEN_KEY
    inputType: Secret
    defaultValue: QUESTDB_PW
    required: true
  - name: QDB_INPUT_TOPIC
    inputType: InputTopic
    defaultValue: solar-data
    required: true
  - name: QDB_USERNAME
    inputType: FreeText
    defaultValue: admin
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: influxdb-3-destination
