name: questdb-sink-draft
language: python
variables:
  - name: QUESTDB_BUFFER_TIMEOUT
    inputType: FreeText
    defaultValue: 1
    required: true
  - name: QUESTDB_BUFFER_SIZE
    inputType: FreeText
    required: true
  - name: QUESTDB_QUESTDB_HOST
    inputType: FreeText
    required: true
  - name: QUESTDB_QUESTDB_DATABASE
    inputType: FreeText
    required: true
  - name: QUESTDB_QUESTDB_USERNAME
    inputType: FreeText
    required: true
  - name: QUESTDB_QUESTDB_PASSWORD_KEY
    inputType: FreeText
    required: true
  - name: QUESTDB_QUESTDB_TABLE_NAME
    inputType: FreeText
    defaultValue: data_sink_trwg
    required: true
  - name: QUESTDB_QUESTDB_PORT
    inputType: FreeText
    required: true
  - name: QUESTDB_INPUT
    inputType: InputTopic
    defaultValue: solar-data
    required: true
  - name: QUESTDB_CONSUMER_GROUP_NAME
    inputType: FreeText
    defaultValue: questdb-consumer-group
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: influxdb-3-destination
