name: google-storage-bucket-source-draft-w78h
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: s3-data
    required: true
  - name: S3_BUCKET
    inputType: FreeText
    description: The URI or URL to your S3 bucket
    required: true
  - name: S3_REGION
    inputType: FreeText
    description: The region of your S3 bucket
    required: true
  - name: S3_SECRET
    inputType: Secret
    description: Your AWS secret
    required: true
  - name: S3_ACCESS_KEY_ID
    inputType: Secret
    description: Your AWS Access Key
    required: true
  - name: S3_FOLDER_PATH
    inputType: FreeText
    description: The path to the S3 folder to consume
    required: true
  - name: S3_FILE_FORMAT
    inputType: FreeText
    description: The file format of the files
    defaultValue: json
    required: true
  - name: S3_FILE_COMPRESSION
    inputType: FreeText
    description: The type of file compression used for the files
    defaultValue: gzip
    required: true
  - name: GOOGLE_STORAGE_BUCKET
    inputType: FreeText
    defaultValue: quix-workflow
    required: true
  - name: GOOGLE_STORAGE_REGION
    inputType: FreeText
    defaultValue: US-CENTRAL1
    required: true
  - name: GOOGLE_STORAGE_SECRET_KEY
    inputType: Secret
    defaultValue: GCLOUD_PK_JSON
    required: true
  - name: GOOGLE_STORAGE_FOLDER_PATH
    inputType: FreeText
    defaultValue: /
    required: true
  - name: GOOGLE_STORAGE_FILE_FORMAT
    inputType: FreeText
    defaultValue: csv
    required: true
  - name: GOOGLE_STORAGE_FILE_COMPRESSION
    inputType: FreeText
    defaultValue: none
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: s3-source
