name: questdb-mothership
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: solar-data
  - name: QUESTDB_HOST
    inputType: FreeText
    description: QuestDB hostname or IP address
    defaultValue: localhost
  - name: QUESTDB_PORT
    inputType: FreeText
    description: QuestDB ILP ingestion port
    defaultValue: 9009
  - name: QUESTDB_DATABASE
    inputType: FreeText
    description: QuestDB database name
    defaultValue: qdb
  - name: QUESTDB_USERNAME
    inputType: FreeText
    description: QuestDB username (if authentication is enabled)
    defaultValue: admin
    required: false
  - name: QUESTDB_PASSWORD
    inputType: Secret
    description: QuestDB password (if authentication is enabled)
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
