name: timescaledb-sink-draft-3329
language: python
variables:
  - name: input
    inputType: InputTopic
    multiline: false
    defaultValue: solar-data
    required: true
  - name: TIMESCALEDB_USER
    inputType: FreeText
    multiline: false
    defaultValue: tsadmin
    required: true
  - name: TIMESCALEDB_HOST
    inputType: FreeText
    multiline: false
    defaultValue: timescaledb
    required: true
  - name: TIMESCALEDB_DATABASE
    inputType: FreeText
    required: true
  - name: TIMESCALEDB_PASSWORD
    inputType: Secret
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: postgresql-destination
