name: gcpsv6
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: csv-data
    required: true
  - name: GCP_CREDENTIALS_JSON
    inputType: FreeText
  - name: GCP_CSV_FILE_PATH
    inputType: FreeText
  - name: GCP_PROJECT_ID
    inputType: FreeText
  - name: GCP_BUCKET_NAME
    inputType: FreeText
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-source
