name: alphavantage-realtime-api-source-draft
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: This is the output topic for hello world data
    defaultValue: stock-data
    required: true
  - name: ALPHAVANTAGE_API_KEY
    inputType: Secret
    defaultValue: AV_API_KEY
    required: true
  - name: ALPHAVANTAGE_API_URL
    inputType: FreeText
    defaultValue: https://www.alphavantage.co
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: web-api-gateway
