name: alphavantage-realtime-api-source-draft
language: python
variables:
- name: output
  inputType: OutputTopic
  description: This is the output topic for hello world data
  defaultValue: stock-data
  required: true
- name: ALPHAVANTAGE_API_URL
  inputType: FreeText
  defaultValue: https://www.alphavantage.co
  required: true
- name: ALPHAVANTAGE_API_KEY
  inputType: Secret
  defaultValue: AV_API_KEY
  required: true
- name: Quix__Sdk__Token
  inputType: Secret
  required: true
  value:
    value: ''
    type: Secret
    description: Quix SDK Token
    required: true
  description: Quix SDK Token
- name: Quix__Portal__Api
  inputType: FreeText
  required: true
  value:
    value: ''
    type: FreeText
    description: Quix Portal API
    required: true
  description: Quix Portal API
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: web-api-gateway
