name: google-sheets-source-draft-t3yf
language: python
variables:
  - name: GOOGLE_SHEET_ID
    inputType: FreeText
    defaultValue: 1i9m16qPwCkrvjE3VXTmm3-v7gNQFGo8nLbRDGtIgFOI
    required: true
  - name: GCP_SHEETS_API_KEY_SECRET
    inputType: Secret
    multiline: false
    defaultValue: GCLOUD_PK_JSON
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-source
