name: questdb-sink-draft-ji1j
language: python
variables:
  - name: QDB_HOST
    inputType: FreeText
    defaultValue: questdb
    required: true
  - name: QDB_TIMESTAMP_COLUMN
    inputType: FreeText
    defaultValue: timestamp
    required: true
  - name: QDB_TOKEN_KEY
    inputType: Secret
    defaultValue: QUESTDB_PW
    required: true
  - name: QDB_PORT
    inputType: FreeText
    defaultValue: 8812
    required: true
  - name: input
    inputType: InputTopic
    defaultValue: solar-data
    required: true
  - name: QDB_BUFFER_SIZE
    inputType: FreeText
    defaultValue: 1000
    required: true
  - name: QDB_DATABASE
    inputType: FreeText
    defaultValue: metrics
    required: true
  - name: QDB_CONSUMER_GROUP_NAME
    inputType: FreeText
    defaultValue: questdb-consumer-group
    required: true
  - name: QDB_BUFFER_TIMEOUT
    inputType: FreeText
    defaultValue: 1
    required: true
  - name: QDB_TABLE
    inputType: FreeText
    defaultValue: data_sink_pjzf
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: influxdb-3-destination
