name: gcp-sinkv1
language: python
variables:
- name: input
  inputType: InputTopic
  description: Name of the input topic to listen to.
  defaultValue: solar-data
- name: GCP_PROJECT_ID
  inputType: FreeText
  description: Google Cloud Project ID
  required: true
  defaultValue: quix-testing-365012
- name: GCP_BUCKET_NAME
  inputType: FreeText
  description: Google Cloud Storage bucket name
  required: true
  defaultValue: quix-workflow
- name: GCP_CREDENTIALS_JSON
  inputType: Secret
  description: GCP Service Account credentials as JSON
  required: true
  defaultValue: GCLOUD_PK_JSON
- name: CSV_FILENAME
  inputType: FreeText
  description: Name of the CSV file to create in the bucket
  defaultValue: solar_data.csv
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
