name: gcp-sinkv1
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: solar-data
  - name: GCP_PROJECT_ID
    inputType: FreeText
    defaultValue: quix-testing-365012
    required: true
  - name: GCP_BUCKET_NAME
    inputType: FreeText
    defaultValue: quix-workflow
    required: true
  - name: GCP_CREDENTIALS_JSON
    inputType: FreeText
    defaultValue: GCLOUD_PK_JSON
    required: true
  - name: CSV_FILENAME
    inputType: FreeText
    defaultValue: solar_data.csv
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
