name: timescale-sink
language: python
variables:
- name: input
  inputType: InputTopic
  description: Name of the input topic to listen to.
  defaultValue: solar-data
- name: DB_HOST
  inputType: FreeText
  description: TimescaleDB host address
  defaultValue: timescaledb
- name: DB_PORT
  inputType: FreeText
  description: TimescaleDB port number
  defaultValue: '5432'
- name: DB_NAME
  inputType: FreeText
  description: TimescaleDB database name
  defaultValue: metrics
- name: DB_USER
  inputType: FreeText
  description: TimescaleDB username
  defaultValue: tsadmin
- name: DB_PASSWORD
  inputType: Secret
  description: TimescaleDB password
  defaultValue: TSDB_SECRET_KEY
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
