name: google-sheets-source-draft-pdck
language: python
variables:
  - name: SHEET_NAME
    inputType: FreeText
    defaultValue: 1i9m16qPwCkrvjE3VXTmm3-v7gNQFGo8nLbRDGtIgFOI
    required: true
  - name: GCP_SHEETS_CREDENTIALS_KEY
    inputType: Secret
    defaultValue: GCLOUD_PK_JSON
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-source
