name: github-public-timeline-sse-event-stre-source-draft
language: python
variables:
  - name: GITHUB_REPO_FILTER
    inputType: FreeText
    defaultValue: all-events
    required: true
  - name: EVENT_STREAM_TIMEOUT
    inputType: FreeText
    defaultValue: 30
    required: true
  - name: GITHUB_API_URL
    inputType: FreeText
    defaultValue: http://github-firehose.libraries.io/events
    required: true
  - name: GITHUB_SSE_PATH
    inputType: FreeText
    defaultValue: /events
    required: true
  - name: GITHUB_AUTH_TOKEN
    inputType: FreeText
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-source
