name: questdb-sink-draft-imx7
language: python
variables:
  - name: QDB_INPUT_TOPIC
    inputType: InputTopic
    defaultValue: solar-data
    required: true
  - name: QDB_HOST
    inputType: FreeText
    defaultValue: questdb
    required: true
  - name: QDB_AUTH_TOKEN_KEY
    inputType: Secret
    defaultValue: QUESTDB_PW
    required: true
  - name: QDB_DATABASE
    inputType: FreeText
    defaultValue: qdb
    required: true
  - name: QDB_TABLE_NAME
    inputType: FreeText
    defaultValue: measurement2
    required: true
  - name: QDB_CONSUMER_GROUP_NAME
    inputType: FreeText
    defaultValue: questdb-sink
    required: true
  - name: QDB_BUFFER_SIZE
    inputType: FreeText
    defaultValue: 1000
    required: true
  - name: QDB_BUFFER_TIMEOUT
    inputType: FreeText
    defaultValue: 1
    required: true
  - name: QDB_PORT
    inputType: FreeText
    defaultValue: 8812
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: influxdb-3-destination
