name: clickhousetest-v10
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: solar-data
  - name: CLICKHOUSE_MAX_RETRIES
    inputType: FreeText
    defaultValue: 3
    required: true
  - name: DEBUG_PRINT
    inputType: FreeText
    defaultValue: false
    required: true
  - name: CLICKHOUSE_HOST
    inputType: FreeText
    defaultValue: clickhouse-test
    required: true
  - name: CLICKHOUSE_SECURE
    inputType: FreeText
    defaultValue: false
    required: true
  - name: CLICKHOUSE_PASSWORD
    inputType: Secret
    defaultValue: CLICKHOUSE_SECRET_KEY
    required: true
  - name: CLICKHOUSE_RETRY_DELAY
    inputType: FreeText
    defaultValue: 3.0
    required: true
  - name: HIGH_TEMP_THRESHOLD
    inputType: FreeText
    defaultValue: 85
    required: true
  - name: LOW_EFFICIENCY_THRESHOLD
    inputType: FreeText
    defaultValue: 15
    required: true
  - name: CLICKHOUSE_DATABASE
    inputType: FreeText
    defaultValue: default
    required: true
  - name: CLICKHOUSE_USERNAME
    inputType: FreeText
    defaultValue: clickadmin
    required: true
  - name: CLICKHOUSE_TABLE
    inputType: FreeText
    defaultValue: solar_panel_data
    required: true
  - name: CLICKHOUSE_BACKPRESSURE_RETRY
    inputType: FreeText
    defaultValue: 30.0
    required: true
  - name: SOLAR_PANEL_AREA
    inputType: FreeText
    defaultValue: 2.0
    required: true
  - name: CONSUMER_GROUP
    inputType: FreeText
    defaultValue: solar_panel_clickhouse_sink
    required: true
  - name: CLICKHOUSE_PORT
    inputType: FreeText
    defaultValue: 8123
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
