name: blockchainv2
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: bitcoin-blockchain-transactions
    required: true
  - name: WEBSOCKET_URL
    inputType: FreeText
    defaultValue: wss://ws.blockchain.info/inv
  - name: BITCOIN_ADDRESS
    inputType: FreeText
  - name: SUBSCRIPTION_TYPE
    inputType: FreeText
    defaultValue: unconfirmed_sub
  - name: MAX_MESSAGES
    inputType: FreeText
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-source
