name: blockchainv2
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: csv-data
    required: true
  - name: SUBSCRIPTION_TYPE
    inputType: FreeText
  - name: WEBSOCKET_URL
    inputType: FreeText
  - name: CONNECTION_TIMEOUT
    inputType: FreeText
    defaultValue: 1
  - name: BITCOIN_ADDRESS
    inputType: FreeText
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-source
