name: clickhouse-sink-draft
language: python
variables:
- name: input
  inputType: InputTopic
  description: This is the input topic
  defaultValue: input-data
  required: true
- name: INFLUXDB_HOST
  inputType: FreeText
  description: Host address for the InfluxDB instance.
  defaultValue: http://influxdb3:80
  required: true
- name: INFLUXDB_TOKEN
  inputType: Secret
  description: Authentication token to access InfluxDB.
  required: true
- name: INFLUXDB_ORG
  inputType: FreeText
  description: Organization name in InfluxDB.
- name: INFLUXDB_MEASUREMENT_NAME
  inputType: FreeText
  description: The InfluxDB measurement to write data to. If not specified, the name
    of the input topic will be used
  defaultValue: measurement1
- name: INFLUXDB_DATABASE
  inputType: FreeText
  description: Database name in InfluxDB where data should be stored.
  required: true
- name: INFLUXDB_TAG_KEYS
  inputType: FreeText
  description: 'The tags to include when writing the measurement data. Example: Tag1,Tag2'
- name: INFLUXDB_FIELD_KEYS
  inputType: FreeText
  description: 'The fields to include when writing the measurement data. Example:
    Field1,Field2'
- name: CONSUMER_GROUP_NAME
  inputType: FreeText
  description: The name of the consumer group to use when consuming from Kafka
  defaultValue: influxdb-sink
  required: true
- name: TIMESTAMP_COLUMN
  inputType: FreeText
  description: 'The column containing the timestamp column. NOTE: Must be nanoseconds'
- name: BUFFER_SIZE
  inputType: FreeText
  description: The number of records that sink holds before flush data to the InfluxDb
  defaultValue: 1000
- name: BUFFER_TIMEOUT
  inputType: FreeText
  description: The number of seconds that sink holds before flush data to the InfluxDb
  defaultValue: 1
- name: Quix__Sdk__Token
  inputType: Secret
  required: true
  value:
    value: ''
    type: Secret
    description: Quix SDK Token
    required: true
  description: Quix SDK Token
- name: Quix__Portal__Api
  inputType: FreeText
  required: true
  value:
    value: ''
    type: FreeText
    description: Quix Portal API
    required: true
  description: Quix Portal API
- name: CLICKHOUSE_TOPIC
  inputType: Topic
  required: true
  value: solar-data
- name: CLICKHOUSE_HOST
  inputType: FreeText
  required: true
  value: clickhouse-test
- name: CLICKHOUSE_TOKEN_KEY
  inputType: Secret
  required: true
  value: CLICKHOUSE_SECRET_KEY
- name: CLICKHOUSE_DATABASE
  inputType: FreeText
  required: true
  value: default
- name: CLICKHOUSE_TABLE
  inputType: FreeText
  required: true
  value: solar_dataV1
- name: CLICKHOUSE_CONSUMER_GROUP_NAME
  inputType: FreeText
  required: true
  value: clickhouse-sink
- name: CLICKHOUSE_BUFFER_SIZE
  inputType: FreeText
  required: true
  value: '1000'
- name: CLICKHOUSE_BUFFER_TIMEOUT
  inputType: FreeText
  required: true
  value: '1'
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: influxdb-3-destination
