name: google-storage-bucket-source-draft-v9e7
language: python
variables:
  - name: GCS_FILE_FORMAT
    inputType: FreeText
    defaultValue: csv
    required: true
  - name: GCS_FOLDER_PATH
    inputType: FreeText
    defaultValue: /
    required: true
  - name: GCP_PROJECT_ID
    inputType: FreeText
    defaultValue: quix-testing-365012
    required: true
  - name: GCS_BUCKET
    inputType: FreeText
    defaultValue: quix-workflow
    required: true
  - name: GCP_CREDENTIALS_KEY
    inputType: Secret
    defaultValue: GCLOUD_PK_JSON
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: s3-source
