name: gcp12
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: solar-data
  - name: GCS_BUCKET_NAME
    inputType: FreeText
    defaultValue: quix-workflow
    required: true
  - name: GCS_CREDENTIALS_JSON
    inputType: FreeText
    defaultValue: GCLOUD_PK_JSON
    required: true
  - name: GCS_CSV_FILENAME
    inputType: FreeText
    defaultValue: solar_data.csv
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
