name: alphavantagev4
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: stock-data
    required: true
  - name: API_KEY
    inputType: FreeText
    defaultValue: AV_API_KEY
  - name: from_currency
    inputType: FreeText
    defaultValue: EUR
  - name: to_currency
    inputType: FreeText
    defaultValue: THB
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-source
