name: timescaledb-sink-draft-wiux
language: python
variables:
  - name: TIMESCALEDB_PASSWORD
    inputType: Secret
    defaultValue: TIMESCALE_PASSWORD
    required: true
  - name: TIMESCALEDB_HOST
    inputType: FreeText
    defaultValue: timescaledb
    required: true
  - name: TIMESCALEDB_TABLE
    inputType: FreeText
    defaultValue: data_sink
    required: true
  - name: TIMESCALEDB_USER
    inputType: FreeText
    defaultValue: tsadmin
    required: true
  - name: BATCH_SIZE
    inputType: FreeText
    required: true
  - name: TIMESCALEDB_DBNAME
    inputType: FreeText
    defaultValue: metrics
    required: true
  - name: CONSUMER_GROUP_NAME
    inputType: FreeText
    defaultValue: timescaledb-consumer-group
    required: true
  - name: input
    inputType: InputTopic
    defaultValue: demo-solarfarmdatageneratordemo-prod-solar-data
    required: true
  - name: TIMESCALEDB_SCHEMA
    inputType: FreeText
    defaultValue: public
    required: true
  - name: TIMESCALEDB_PORT
    inputType: FreeText
    defaultValue: 5432
    required: true
  - name: BATCH_TIMEOUT
    inputType: FreeText
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: postgresql-destination
