name: questdb-lies
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: solar-data
  - name: QUESTDB_PORT
    inputType: FreeText
    defaultValue: 9000
    required: true
  - name: QUESTDB_HOST
    inputType: FreeText
    defaultValue: questdb
    required: true
  - name: QUESTDB_TOKEN
    inputType: Secret
    defaultValue: QUESTDB_PW
    required: true
  - name: QUESTDB_TABLE_NAME
    inputType: FreeText
    defaultValue: solar_panel_data
    required: true
  - name: CONSUMER_GROUP_NAME
    inputType: FreeText
    defaultValue: questdb_solar_sink
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
