name: google-storage-bucket-source-draft
language: python
variables:
  - name: GCP_PROJECT_ID
    inputType: FreeText
    defaultValue: quix-testing-365012
    required: true
  - name: GCS_BUCKET_NAME
    inputType: FreeText
    defaultValue: quix-workflow
    required: true
  - name: GCS_FOLDER_PATH
    inputType: FreeText
    defaultValue: /
    required: true
  - name: GCS_FILE_FORMAT
    inputType: FreeText
    defaultValue: csv
    required: true
  - name: GCP_SECRET_NAME_KEY
    inputType: Secret
    defaultValue: GCLOUD_PK_JSON
    required: true
  - name: output
    inputType: OutputTopic
    multiline: false
    defaultValue: bucket-output
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: s3-source
