name: google-storage-bucket-source-draft
language: python
variables:
  - name: GOOGLE_STORAGE_BUCKET
    inputType: FreeText
    defaultValue: quix-workflow
    required: true
  - name: GOOGLE_STORAGE_FOLDER_PATH
    inputType: FreeText
    defaultValue: /
    required: true
  - name: GOOGLE_STORAGE_SECRET_KEY
    inputType: Secret
    defaultValue: GCLOUD_PK_JSON
    required: true
  - name: GOOGLE_STORAGE_FILE_FORMAT
    inputType: FreeText
    defaultValue: csv
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: s3-source
