name: wikipediav1
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: csv-data
    required: true
  - name: WIKIPEDIA_STREAM_URL
    inputType: FreeText
  - name: WIKI_FILTER
    inputType: FreeText
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-source
