name: clickhousetest-v13
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: solar-data
  - name: CLICKHOUSE_CONNECT_TIMEOUT
    inputType: FreeText
    defaultValue: 1
  - name: CLICKHOUSE_TABLE
    inputType: FreeText
  - name: CLICKHOUSE_HOST
    inputType: FreeText
  - name: CLICKHOUSE_USERNAME
    inputType: FreeText
  - name: CLICKHOUSE_SEND_TIMEOUT
    inputType: FreeText
    defaultValue: 1
  - name: CLICKHOUSE_PORT
    inputType: FreeText
  - name: CLICKHOUSE_DATABASE
    inputType: FreeText
  - name: CLICKHOUSE_PASSWORD
    inputType: FreeText
  - name: TESTING_MODE
    inputType: FreeText
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
