name: gcp-test-v3
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: solar-data
  - name: GCP_SERVICE_ACCOUNT_JSON
    inputType: FreeText
    defaultValue: GCLOUD_PK_JSON
    required: true
  - name: GCP_CSV_FILE_PREFIX
    inputType: FreeText
    defaultValue: /
    required: true
  - name: GCP_BUCKET_NAME
    inputType: FreeText
    defaultValue: quix-workflow
    required: true
  - name: QUIX_TEST_MODE
    inputType: FreeText
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
