name: clickhouse-sink-draft
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic
    defaultValue: input-data
    required: true
  - name: CLICKHOUSE_CONSUMER_GROUP_NAME
    inputType: FreeText
    defaultValue: clickhouse-sink
    required: true
  - name: CLICKHOUSE_BUFFER_SIZE
    inputType: FreeText
    defaultValue: 1000
    required: true
  - name: CLICKHOUSE_BUFFER_TIMEOUT
    inputType: FreeText
    defaultValue: 1
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: influxdb-3-destination
