name: clickhouse-sink-draft
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: solar-data
  - name: CLICKHOUSE_PASSWORD
    inputType: Secret
    defaultValue: CLICKHOUSE_SECRET_KEY
    required: true
  - name: CLICKHOUSE_PORT
    inputType: FreeText
    defaultValue: 9000
    required: true
  - name: CLICKHOUSE_HOST
    inputType: FreeText
    defaultValue: clickhouse-test
    required: true
  - name: CLICKHOUSE_USER
    inputType: FreeText
    defaultValue: clickadmin
    required: true
  - name: CLICKHOUSE_DATABASE
    inputType: FreeText
    defaultValue: default
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
