name: questdb-madness
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: solar-data
  - name: QDB_HOST
    inputType: FreeText
    defaultValue: questdb
    required: true
  - name: QDB_TOKEN
    inputType: Secret
    defaultValue: QUESTDB_PW
    required: true
  - name: QDB_PORT
    inputType: FreeText
    defaultValue: 9000
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
