name: questdb-madness
language: python
variables:
- name: input
  inputType: InputTopic
  description: Name of the input topic to listen to.
  defaultValue: solar-data
- name: QDB_HOST
  inputType: FreeText
  description: QuestDB host address
  defaultValue: questdb
- name: QDB_PORT
  inputType: FreeText
  description: QuestDB port
  defaultValue: '9000'
- name: QDB_TOKEN
  inputType: Secret
  description: QuestDB authentication token (optional)
  required: false
  defaultValue: QUESTDB_PW
- name: QDB_DATABASE
  inputType: FreeText
  description: QuestDB database name (optional for HTTP)
  defaultValue: qdb
  required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
