name: google-storage-buckets-source-draft-44wj
language: python
variables:
  - name: GOOGLE_STORAGE_FILE_FORMAT
    inputType: FreeText
    defaultValue: csv
    required: true
  - name: GS_API_KEY
    inputType: Secret
    multiline: false
    defaultValue: GCLOUD_PK_JSON
    required: true
  - name: GOOGLE_STORAGE_OUTPUT_BUCKET
    inputType: OutputTopic
    defaultValue: output
    required: true
  - name: GOOGLE_STORAGE_FOLDER_PATH
    inputType: FreeText
    defaultValue: 'data/  # Sensible default path'
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: s3-source
