name: gcp-test-v4
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: solar-data
  - name: GCS_BUCKET_NAME
    inputType: FreeText
    defaultValue: quix-workflow
    required: true
  - name: GCS_CSV_FILE_PATH
    inputType: FreeText
    defaultValue: solar_data/solar_sensor_data.csv
    required: true
  - name: GOOGLE_APPLICATION_CREDENTIALS
    inputType: FreeText
    defaultValue: GCLOUD_PK_JSON
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
