name: Solar Data TimescaleDB Sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Input topic containing solar panel data
    defaultValue: solar-data
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: postgresql-destination
