name: Solar Data TimescaleDB Sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Input topic containing solar panel data
    defaultValue: solar-data
    required: true
  - name: TIMESCALE_HOST
    inputType: FreeText
    description: TimescaleDB host address
    defaultValue: timescaledb
    required: true
  - name: TIMESCALE_PORT
    inputType: FreeText
    description: TimescaleDB port number
    defaultValue: 5432
    required: true
  - name: TIMESCALE_DBNAME
    inputType: FreeText
    description: TimescaleDB database name
    defaultValue: metrics
    required: true
  - name: TIMESCALE_USER
    inputType: FreeText
    description: TimescaleDB username
    defaultValue: tsadmin
    required: true
  - name: TIMESCALE_TABLE
    inputType: FreeText
    description: Target table name for solar data
    defaultValue: solar_data
    required: true
  - name: TIMESCALE_SCHEMA
    inputType: FreeText
    description: Database schema name
    defaultValue: public
  - name: SCHEMA_AUTO_UPDATE
    inputType: FreeText
    description: Automatically update table schema
    defaultValue: true
  - name: CONSUMER_GROUP_NAME
    inputType: FreeText
    description: Kafka consumer group name
    defaultValue: solar-timescale-sink
  - name: BATCH_TIMEOUT
    inputType: FreeText
    description: Batch commit timeout in seconds
    defaultValue: 1
  - name: BATCH_SIZE
    inputType: FreeText
    description: Batch size for committing data
    defaultValue: 1000
  - name: TIMESCALE_PASSWORD
    inputType: FreeText
    description: TimescaleDB password
    defaultValue: tsadminpass
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: postgresql-destination
