name: Solar Data TimescaleDB Sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Input topic containing solar panel data
    defaultValue: solar-data
    required: true
  - name: TIMESCALE_TABLE
    inputType: FreeText
    description: Target table name for solar data
    defaultValue: solar_data
    required: true
  - name: TIMESCALE_SCHEMA
    inputType: FreeText
    description: Database schema name
    defaultValue: public
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: postgresql-destination
