FROM postgres:16

# Set environment variables
ENV PGDATA=/app/state/pgdata
ENV POSTGRES_USER=admin
ENV POSTGRES_DB=quix
ENV POSTGRES_PORT=80

# Update PostgreSQL configuration to use port 80
RUN echo "port = 80" >> /usr/share/postgresql/postgresql.conf.sample

# Expose port 80
EXPOSE 80

# Copy and set up init script
USER root
COPY init.sh /init.sh
RUN chmod +x /init.sh

# Set the entrypoint
ENTRYPOINT ["/init.sh"]