name: btctestv1-64n3
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: bitcoin-blockchain-transactions
    required: true
  - name: API_KEY
    inputType: Secret
    defaultValue: TSDB_SECRET_KEY
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-source
