name: timescaledb-sink-draft-z952
language: python
variables:
  - name: BATCH_SIZE
    inputType: FreeText
    defaultValue: 1000
    required: true
  - name: TIMESCALEDB_HOST
    inputType: FreeText
    defaultValue: timescaledb
    required: true
  - name: TIMESCALEDB_PASSWORD
    inputType: Secret
    defaultValue: TIMESCALE_PASSWORD
    required: true
  - name: TIMESCALEDB_USERNAME
    inputType: FreeText
    defaultValue: tsadmin
    required: true
  - name: TIMESCALEDB_TABLE_NAME
    inputType: FreeText
    defaultValue: timescaledb_sink
    required: true
  - name: TIMESCALEDB_PORT
    inputType: FreeText
    defaultValue: 5432
    required: true
  - name: TIMESCALEDB_TABLENAME
    inputType: FreeText
    defaultValue: timescaledb_sink
    required: true
  - name: TIMESCALEDB_JSONCOLUMN
    inputType: FreeText
    required: true
  - name: TIMESCALEDB_DBNAME
    inputType: FreeText
    defaultValue: metrics
    required: true
  - name: input
    inputType: InputTopic
    defaultValue: solar-farm
    required: true
  - name: BATCH_TIMEOUT
    inputType: FreeText
    defaultValue: 1
    required: true
  - name: CONSUMER_GROUP_NAME
    inputType: FreeText
    defaultValue: timescaledb-consumer-group
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: postgresql-destination
