name: google-storage-bucket-csvsink-v1
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: solar-data
  - name: GCS_FILE_PREFIX
    inputType: FreeText
    defaultValue: solar_data
    required: true
  - name: GOOGLE_APPLICATION_CREDENTIALS
    inputType: Secret
    multiline: false
    required: true
  - name: GCS_BUCKET_NAME
    inputType: FreeText
    defaultValue: quix-workflow
    required: true
  - name: GCLOUD_PK_JSON
    inputType: FreeText
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
