name: clickhouse-sink-draft-isup
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic
    defaultValue: input-data
    required: true
  - name: CLICKHOUSE_BUFFER_TIMEOUT
    inputType: FreeText
    defaultValue: 1
    required: true
  - name: CLICKHOUSE_DATABASE
    inputType: FreeText
    defaultValue: default
    required: true
  - name: CLICKHOUSE_BUFFER_SIZE
    inputType: FreeText
    defaultValue: 1000
    required: true
  - name: CLICKHOUSE_TABLE
    inputType: FreeText
    defaultValue: solar_dataV1
    required: true
  - name: CLICKHOUSE_CONSUMER_GROUP_NAME
    inputType: FreeText
    defaultValue: clickhouse-sink
    required: true
  - name: CLICKHOUSE_TOPIC
    inputType: InputTopic
    defaultValue: solar-data
    required: true
  - name: CLICKHOUSE_HOST
    inputType: FreeText
    defaultValue: clickhouse-test
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: influxdb-3-destination
