name: gcpsv3
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: csv-data
    required: true
  - name: CSV_FILE_PATH
    inputType: FreeText
    defaultValue: 3d_printer_data_anomalies.csv
  - name: GCP_SERVICE_ACCOUNT_KEY
    inputType: FreeText
    defaultValue: GCLOUD_PK_JSON
  - name: GCP_BUCKET_NAME
    inputType: FreeText
    defaultValue: quix-worklfow
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-source
