name: google-storage-bucket-source-draft-59pj
language: python
variables:
  - name: GS_PROJECT_ID
    inputType: FreeText
    defaultValue: quix-testing-365012
    required: true
  - name: GOOGLE_APPLICATION_CREDENTIALS
    inputType: FreeText
    required: true
  - name: GS_FOLDER_PATH
    inputType: FreeText
    defaultValue: /
    required: true
  - name: GS_FILE_FORMAT
    inputType: FreeText
    defaultValue: csv
    required: true
  - name: GS_BUCKET
    inputType: FreeText
    defaultValue: quix-workflow
    required: true
  - name: GCLOUD_PK_JSON
    inputType: FreeText
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: s3-source
