name: timescaledb-sink-draft-houw
language: python
variables:
  - name: TIMESCALEDB_PORT
    inputType: FreeText
    defaultValue: 5432
    required: true
  - name: TIMESCALEDB_HOST
    inputType: FreeText
    defaultValue: timescaledb
    required: true
  - name: TIMESCALEDB_DBNAME
    inputType: FreeText
    defaultValue: metrics
    required: true
  - name: TIMESCALEDB_USERNAME
    inputType: FreeText
    defaultValue: tsadmin
    required: true
  - name: TIMESCALEDB_TABLENAME
    inputType: FreeText
    defaultValue: timescaledb_sink
    required: true
  - name: TIMESCALEDB_PASSWORD
    inputType: Secret
    defaultValue: TIMESCALE_PASSWORD
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: postgresql-destination
