name: questdb-sink-draft-mhnf
language: python
variables:
  - name: QUESTDB_USER
    inputType: FreeText
    defaultValue: admin
    required: true
  - name: QUESTDB_HOST
    inputType: FreeText
    defaultValue: questdb
    required: true
  - name: BUFFER_SIZE
    inputType: FreeText
    defaultValue: 1000
    required: true
  - name: QUESTDB_INPUT_TOPIC
    inputType: InputTopic
    defaultValue: solar-data
    required: true
  - name: BUFFER_TIMEOUT
    inputType: FreeText
    defaultValue: 1
    required: true
  - name: QUESTDB_DATABASE
    inputType: FreeText
    defaultValue: qdb
    required: true
  - name: QUESTDB_TABLE_NAME
    inputType: FreeText
    defaultValue: data_sink_euty
    required: true
  - name: CONSUMER_GROUP_NAME
    inputType: FreeText
    defaultValue: questdb-consumer-group
    required: true
  - name: QUESTDB_PORT
    inputType: FreeText
    defaultValue: 8812
    required: true
  - name: QUESTDB_PASSWORD_KEY
    inputType: Secret
    defaultValue: QUESTDB_PW
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: influxdb-3-destination
