name: google-cloud-storage-source-draft-290w
language: python
variables:
  - name: GCS_SERVICE_ACCOUNT_EMAIL
    inputType: FreeText
    defaultValue: doc-publisher@quix-testing-365012.iam.gserviceaccount.com
    required: true
  - name: GCS_PROJECT_ID
    inputType: FreeText
    defaultValue: quix-testing-365012
    required: true
  - name: GCS_BUCKET_NAME
    inputType: FreeText
    defaultValue: quix-workflow
    required: true
  - name: GCS_KEY_FILE_PATH
    inputType: Secret
    defaultValue: GCLOUD_PK_JSON
    required: true
  - name: GCS_FOLDER_PATH
    inputType: FreeText
    defaultValue: /
    required: true
  - name: GCS_FILE_FORMAT
    inputType: FreeText
    defaultValue: csv
    required: true
  - name: GCS_COMPRESSION
    inputType: FreeText
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: s3-source
