name: timescaledb-sink-draft-uj95
language: python
variables:
  - name: TSDB_PASSWORD_KEY
    inputType: FreeText
    required: true
  - name: CONSUMER_GROUP_NAME
    inputType: FreeText
    defaultValue: timescaledb-consumer-group
    required: true
  - name: TSDB_USER
    inputType: FreeText
    required: true
  - name: TSDB_HOST
    inputType: FreeText
    required: true
  - name: input
    inputType: InputTopic
    defaultValue: solar-data
    required: true
  - name: TSDB_SCHEMA
    inputType: FreeText
    defaultValue: public
    required: true
  - name: BATCH_SIZE
    inputType: FreeText
    defaultValue: 1000
    required: true
  - name: TSDB_TABLE
    inputType: FreeText
    defaultValue: data_sink_13ve
    required: true
  - name: TSDB_PORT
    inputType: FreeText
    required: true
  - name: BATCH_TIMEOUT
    inputType: FreeText
    defaultValue: 1
    required: true
  - name: TSDB_DBNAME
    inputType: FreeText
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: postgresql-destination
