name: questdb-sink-draft-dj29
language: python
variables:
  - name: QUESTDB_INPUT_TOPIC
    inputType: InputTopic
    defaultValue: solar-data
    required: true
  - name: QUESTDB_HOST
    inputType: FreeText
    defaultValue: questdb
    required: true
  - name: QUESTDB_AUTH_KEY
    inputType: Secret
    defaultValue: QUESTDB_PW
    required: true
  - name: QUESTDB_DATABASE
    inputType: FreeText
    defaultValue: qdb
    required: true
  - name: QUESTDB_TABLE_NAME
    inputType: FreeText
    defaultValue: measurement1
    required: true
  - name: QUESTDB_CONSUMER_GROUP_NAME
    inputType: FreeText
    defaultValue: questdb-consumer-group
    required: true
  - name: QUESTDB_TIMESTAMP_COLUMN
    inputType: FreeText
    defaultValue: timestamp_ns
    required: true
  - name: QUESTDB_BUFFER_SIZE
    inputType: FreeText
    defaultValue: 1000
    required: true
  - name: QUESTDB_BUFFER_TIMEOUT
    inputType: FreeText
    defaultValue: 1
    required: true
  - name: QUESTDB_PORT
    inputType: FreeText
    defaultValue: 8812
    required: true
  - name: QUESTDB_PASSWORD
    inputType: Secret
    multiline: false
    defaultValue: QUESTDB_PW
    required: true
  - name: QUESTDB_USER
    inputType: FreeText
    defaultValue: admin
    required: true
  - name: CONSUMER_GROUP_NAME
    inputType: FreeText
    defaultValue: questdb-consumer
  - name: BUFFER_DELAY
    inputType: FreeText
    defaultValue: 1
  - name: BUFFER_SIZE
    inputType: FreeText
    defaultValue: 1000
  - name: input
    inputType: FreeText
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: influxdb-3-destination
