name: questdb-torture
language: python
variables:
- name: input
  inputType: InputTopic
  description: Name of the input topic to listen to.
  defaultValue: solar-data
- name: QUESTDB_HOST
  inputType: FreeText
  description: QuestDB host address
  defaultValue: questdb
- name: QUESTDB_PORT
  inputType: FreeText
  description: QuestDB port number
  defaultValue: '9000'
- name: QUESTDB_TOKEN
  inputType: Secret
  description: QuestDB authentication token (optional)
  required: false
  defaultValue: QUESTDB_PW
- name: QUESTDB_USERNAME
  inputType: FreeText
  description: QuestDB username (optional, for basic auth)
  required: false
- name: QUESTDB_PASSWORD
  inputType: Secret
  description: QuestDB password (optional, for basic auth)
  required: false
  defaultValue: QUESTDB_PW
- name: QUESTDB_TABLE
  inputType: FreeText
  description: QuestDB table name for solar panel data
  defaultValue: solar_panel_data
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
