name: questdb-torture
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: solar-data
  - name: QUESTDB_HOST
    inputType: FreeText
    defaultValue: questdb
    required: true
  - name: QUESTDB_PASSWORD
    inputType: Secret
    defaultValue: QUESTDB_PW
    required: true
  - name: QUESTDB_TOKEN
    inputType: Secret
    defaultValue: QUESTDB_PW
    required: true
  - name: QUESTDB_TABLE
    inputType: FreeText
    defaultValue: solar_panel_data
    required: true
  - name: QUESTDB_PORT
    inputType: FreeText
    defaultValue: 9000
    required: true
  - name: QUESTDB_USERNAME
    inputType: FreeText
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
