name: timescaledb-sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to
    defaultValue: solar-data
  - name: TIMESCALE_HOST
    inputType: FreeText
    description: TimescaleDB server hostname
    required: true
  - name: TIMESCALE_PORT
    inputType: FreeText
    description: TimescaleDB server port
    defaultValue: 5432
  - name: TIMESCALE_DATABASE
    inputType: FreeText
    description: TimescaleDB database name
    required: true
  - name: TIMESCALE_USER
    inputType: FreeText
    description: TimescaleDB username
    required: true
  - name: TIMESCALE_PASSWORD
    inputType: Secret
    description: TimescaleDB password
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: postgresql-destination
