name: timescaledb-sink-test
language: python
variables:
  - name: TIMESCALE_HOST
    inputType: FreeText
    description: TimescaleDB host address
    defaultValue: timescaledb
    required: true
  - name: TIMESCALE_PORT
    inputType: FreeText
    description: TimescaleDB port
    defaultValue: 5432
    required: true
  - name: TIMESCALE_DATABASE
    inputType: FreeText
    description: TimescaleDB database name
    defaultValue: metrics
    required: true
  - name: TIMESCALE_USERNAME
    inputType: FreeText
    description: TimescaleDB username
    defaultValue: tsadmin
    required: true
  - name: TIMESCALE_PASSWORD
    inputType: Secret
    description: TimescaleDB password (stored as Quix Secret)
    required: true
  - name: TIMESCALE_TABLE
    inputType: FreeText
    description: Target table name in TimescaleDB
    defaultValue: solar_panel_data
    required: true
  - name: INPUT_TOPIC
    inputType: InputTopic
    description: Input topic to read solar panel data from
    defaultValue: solar-data
    required: true
  - name: input
    inputType: InputTopic
    defaultValue: solar-data
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: postgresql-destination
