name: gcpcsv-sink
language: python
variables:
- name: input
  inputType: InputTopic
  description: Name of the input topic to listen to.
  defaultValue: solar-data
- name: GCP_CREDENTIALS_JSON
  inputType: Secret
  description: Google Cloud Service Account credentials in JSON format
  defaultValue: GCLOUD_PK_JSON
- name: GCP_BUCKET_NAME
  inputType: FreeText
  description: Name of the Google Cloud Storage bucket to write CSV files to
  required: true
  defaultValue: quix-workflow
- name: GCP_FILE_PREFIX
  inputType: FreeText
  description: Prefix for CSV filenames (optional, defaults to 'solar-data')
  defaultValue: solar-data
  required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
