name: openweatherv1
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: csv-data
    required: true
  - name: OPENWEATHER_API_KEY
    inputType: FreeText
  - name: CITY_NAME
    inputType: FreeText
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-source
