name: openweatherv1
language: python
variables:
- name: OPENWEATHER_API_KEY
  inputType: Secret
  description: OpenWeather API key for authentication
  required: true
  defaultValue: OW_API_SECRET_KEY
- name: CITY_NAME
  inputType: FreeText
  description: City name to get weather data for
  defaultValue: Berlin
  required: true
- name: output
  inputType: OutputTopic
  description: Name of the output topic to write into
  defaultValue: openweather-data
  required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-source
