name: solar-data-timescaledb-sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Input topic containing solar panel data
    defaultValue: solar-data
    required: true
  - name: TIMESCALEDB_HOST
    inputType: FreeText
    description: TimescaleDB server hostname
    defaultValue: timescaledb
    required: true
  - name: TIMESCALEDB_PORT
    inputType: FreeText
    description: TimescaleDB server port
    defaultValue: 5432
    required: true
  - name: TIMESCALEDB_DBNAME
    inputType: FreeText
    description: TimescaleDB database name
    defaultValue: metrics
    required: true
  - name: TIMESCALEDB_USER
    inputType: FreeText
    description: TimescaleDB username
    defaultValue: tsadmin
    required: true
  - name: TIMESCALEDB_PASSWORD
    inputType: Secret
    description: TimescaleDB password (secret key name)
    defaultValue: TIMESCALE_PASSWORD
    required: true
  - name: TIMESCALEDB_TABLE
    inputType: FreeText
    description: Target table name for solar data
    defaultValue: solar_panel_data
    required: true
  - name: TIMESCALEDB_SCHEMA
    inputType: FreeText
    description: Database schema name
    defaultValue: public
  - name: SCHEMA_AUTO_UPDATE
    inputType: FreeText
    description: Auto-update table schema if needed
    defaultValue: true
  - name: CONSUMER_GROUP_NAME
    inputType: FreeText
    description: Kafka consumer group name
    defaultValue: solar-timescaledb-sink
  - name: BATCH_TIMEOUT
    inputType: FreeText
    description: Batch commit timeout in seconds
    defaultValue: 1
  - name: BATCH_SIZE
    inputType: FreeText
    description: Number of records per batch
    defaultValue: 1000
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: postgresql-destination
