name: google-storage-bucket-source-draft-vu46
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: badboy
    required: true
  - name: GOOGLE_FILE_COMPRESSION
    inputType: FreeText
    defaultValue: none
    required: true
  - name: GOOGLE_SECRET_KEY
    inputType: Secret
    defaultValue: GCLOUD_PK_JSON
    required: true
  - name: GOOGLE_FOLDER_PATH
    inputType: FreeText
    defaultValue: /
    required: true
  - name: GOOGLE_BUCKET_NAME
    inputType: FreeText
    defaultValue: quix-workflow
    required: true
  - name: GOOGLE_FILE_FORMAT
    inputType: FreeText
    defaultValue: csv
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: s3-source
