name: API Sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: configuration
  - name: API_BASE_URL
    inputType: FreeText
    multiline: false
    defaultValue: https://gateway-demo-joinsdemo-prod.demo.quix.io
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
