name: google-sheets-source-draft
language: python
variables:
  - name: GOOGLE_SHEETS_CREDS
    inputType: FreeText
    defaultValue: GCLOUD_PK_JSON
    required: true
  - name: GOOGLE_SHEETS_API_VERSION
    inputType: FreeText
    defaultValue: v4
    required: true
  - name: SHEET_NAME
    inputType: FreeText
    defaultValue: Sheet1
    required: true
  - name: SPREADSHEET_NAME
    inputType: FreeText
    defaultValue: csv-test-workflow
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-source
