name: google-sheets-source-draft
language: python
variables:
  - name: GOOGLE_SHEETS_CREDS
    inputType: Secret
    multiline: false
    defaultValue: GCLOUD_PK_JSON
    required: true
  - name: GOOGLE_SHEETS_API_VERSION
    inputType: FreeText
    defaultValue: v4
    required: true
  - name: SHEET_NAME
    inputType: FreeText
    defaultValue: Sheet1
    required: true
  - name: SPREADSHEET_NAME
    inputType: FreeText
    multiline: false
    defaultValue: 1i9m16qPwCkrvjE3VXTmm3-v7gNQFGo8nLbRDGtIgFOI
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-source
