name: btctestv1
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: csv-data
    required: true
  - name: WEBSOCKET_URL
    inputType: FreeText
  - name: SAMPLE_COUNT
    inputType: FreeText
  - name: CONNECTION_TIMEOUT
    inputType: FreeText
    defaultValue: 1
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-source
