name: clickhouse-sink-draft-p996
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic
    defaultValue: solar-data
    required: true
  - name: CONSUMER_GROUP_NAME
    inputType: FreeText
    description: The name of the consumer group to use when consuming from Kafka
    defaultValue: influxdb-sink
    required: true
  - name: BUFFER_SIZE
    inputType: FreeText
    description: The number of records that sink holds before flush data to the InfluxDb
    defaultValue: 1000
  - name: BUFFER_TIMEOUT
    inputType: FreeText
    description: The number of seconds that sink holds before flush data to the InfluxDb
    defaultValue: 1
  - name: CLICKHOUSE_USER
    inputType: FreeText
    defaultValue: clickadmin
    required: true
  - name: CLICKHOUSE_TOKEN_KEY
    inputType: Secret
    multiline: false
    defaultValue: CLICKHOUSE_SECRET_KEY
    required: true
  - name: CLICKHOUSE_DATABASE
    inputType: FreeText
    defaultValue: default
    required: true
  - name: CLICKHOUSE_PORT
    inputType: FreeText
    multiline: false
    defaultValue: 9000
    required: true
  - name: CLICKHOUSE_HOST
    inputType: FreeText
    defaultValue: clickhouse-test
    required: true
  - name: CLICKHOUSE_PASSWORD
    inputType: FreeText
  - name: CLICKHOUSE_INTERFACE
    inputType: FreeText
  - name: CLICKHOUSE_SECURE
    inputType: FreeText
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: influxdb-3-destination
